name: Deploy to AWS

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd tracknest_server  # Thay đổi đường dẫn nếu cần
          git pull origin main
          npm install  # Nếu dùng Node.js
          pm2 restart all  # Restart server với PM2
